# Generated by Django 3.1.1 on 2021-02-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genres', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('slength', models.IntegerField(blank=True, null=True, verbose_name='Series_Length')),
                ('mlength', models.IntegerField(blank=True, null=True, verbose_name='Movie_Length')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('banner', models.ImageField(upload_to='images')),
                ('my_type', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=50)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avenueShop.genre')),
            ],
        ),
    ]
